use_frameworks!

target 'PoporNetMonitor_Example' do
  pod 'PoporNetMonitor', :path => '../'

  target 'PoporNetMonitor_Tests' do
    inherit! :search_paths
  end
  
  pod 'PoporFoundation/NSData'
  
  pod 'PoporAFN' # 包括pod 'AFNetworking',  pod 'PoporNetRecord',
  
end
